//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04.Materi.University.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_UniversityEntities : DbContext
    {
        public DB_UniversityEntities()
            : base("name=DB_UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_m_agama> tbl_m_agama { get; set; }
        public virtual DbSet<tbl_m_dosen> tbl_m_dosen { get; set; }
        public virtual DbSet<tbl_m_jurusan> tbl_m_jurusan { get; set; }
        public virtual DbSet<tbl_m_mahasiswa> tbl_m_mahasiswa { get; set; }
        public virtual DbSet<tbl_m_type_dosen> tbl_m_type_dosen { get; set; }
        public virtual DbSet<tbl_r_ujian> tbl_r_ujian { get; set; }
        public virtual DbSet<tbl_t_nilai> tbl_t_nilai { get; set; }
    }
}
