//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04.Materi.University.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_nilai
    {
        public int id_nilai_pk { get; set; }
        public long id_mahasiswa_fk { get; set; }
        public int id_ujian_fk { get; set; }
        public decimal nilai { get; set; }
        public bool is_active { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string updated_by { get; set; }
        public System.DateTime updated_date { get; set; }
    }
}
